{{- range $storageclass := .Values.storageclass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $storageclass.name | default "missingname" }}
{{- if $storageclass.annotations }}
  annotations:
{{- with $storageclass.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- if $storageclass.labels }}
  labels:
{{- with $storageclass.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
provisioner: {{ $storageclass.provisioner  | default "kubernetes.io/no-provisioner" }}
reclaimPolicy: {{ $storageclass.reclaimPolicy | default "Retain" }}
allowVolumeExpansion: {{ $storageclass.allowVolumeExpansion | default "false" }}
volumeBindingMode: {{ $storageclass.olumeBindingMode | default "WaitForFirstConsumer" }}
{{- if $storageclass.parameters }}
parameters:
{{- with $storageclass.parameters }}
{{ toYaml . | trim | indent 4 }}
{{- end }}
{{- end }}
{{- if $storageclass.allowedTopologies }}
allowedTopologies:
{{- with $storageclass.allowedTopologies }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
{{ end -}}
